ci: force failure with message

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,12 +18,12 @@ jobs:
       - name: Check setup
         run: |
           if [ -z "${AZURE_CREDENTIALS}" ]; then
-            echo "CANCEL_DEPLOY=true" >> "$GITHUB_ENV"
+            echo "Azure credentials not found."
+            echo "Please run .azure/setup.sh to setup your deployment."
+            exit 1
           fi
         env:
           AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
-      - if: ${{ env.CANCEL_DEPLOY }}
-        uses: andymckay/cancel-action@0.2
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
         with:
